### ISSUE TITLE
Can't get past the PHP errors

### ISSUE THREAD

**Issue by JoKneeMo** [billda/package-dashboard#1]
Bill,

Any idea why I'm getting the errors below?

I've tested the database connection manually and it's fine. I can't seem to figure out why it's not pulling the package array.

Running worker.php doesn't produce any errors in the logs, but it doesn't seem to query the db either.

`PHP Notice:  Undefined variable: messages in /package-dashboard/index.php on line 167
PHP Notice:  Undefined variable: package in /package-dashboard/index.php on line 216
PHP Notice:  Undefined variable: package in /package-dashboard/index.php on line 218
PHP Notice:  Undefined variable: package in /package-dashboard/index.php on line 223
PHP Notice:  Undefined variable: package in /package-dashboard/index.php on line 224
PHP Notice:  Undefined variable: package in /package-dashboard/index.php on line 225
PHP Notice:  Undefined variable: package in /package-dashboard/index.php on line 226
PHP Notice:  Undefined variable: checkpoint in /package-dashboard/index.php on line 234
PHP Notice:  Undefined variable: checkpoint in /package-dashboard/index.php on line 235
PHP Notice:  Undefined variable: checkpoint in /package-dashboard/index.php on line 236
PHP Notice:  Undefined variable: checkpoint in /package-dashboard/index.php on line 237
PHP Notice:  Undefined variable: package in /package-dashboard/index.php on line 246
PHP Notice:  Undefined variable: package in /package-dashboard/index.php on line 246
PHP Notice:  Undefined variable: package in /package-dashboard/index.php on line 246
PHP Notice:  Undefined variable: package in /package-dashboard/index.php on line 246
PHP Notice:  Undefined variable: package in /package-dashboard/index.php on line 246
PHP Fatal error:  Call to undefined function get_tracking_url() in /package-dashboard/index.php on line 246`

My config file seems to be correct
![notepad _2016-09-13_15-45-26](https://cloud.githubusercontent.com/assets/421625/18488923/8249a540-79c9-11e6-97b4-89a9410d7a1f.png)

And I installed the dependencies with composer.

Not sure what's happening.

**Comment by billda** [comment]
Hi @JoKneeMo - it looks like your database queries are failing or not happening at all. Are you sure there is example data in your database? These warnings might just be your database queries coming up empty, and thus PHP encountering empty arrays when trying to render the HTML. Try loading index.php in your browser and using the "add a package" button.

**Comment by JoKneeMo** [comment]
I apologize, I didn't see your response when you sent it.

I will try this out again this weekend and let you know the status. 

Thanks!
